# Generated by Django 2.1 on 2018-10-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='article',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('L', 'Like'), ('U', 'Up Vote'), ('D', 'Down Vote'), ('E', 'Down Vote Article'), ('V', 'Up Vote Article')], max_length=1),
        ),
    ]
