# Generated by Django 2.1 on 2018-10-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20181014_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('C', 'Commented'), ('U', 'Upvoted Answer'), ('D', 'Downvoted Answer'), ('R', 'Upvoted Article'), ('T', 'Downvoted Article'), ('A', 'Answered'), ('S', 'Also Commented')], max_length=1),
        ),
    ]
