# Generated by Django 2.1 on 2018-10-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20181014_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='update_user',
        ),
        migrations.AlterField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
