# Generated by Django 2.1 on 2018-10-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20181014_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
